# Environment configuration file for gandi-dyndns.sh & gandi-dyndns.service
#
# Empty lines, lines without an "=" separator, or lines starting with ";"
# or "#" will be ignored, which may be used for commenting.
#
# I suggest APIKEY and DOMAIN be configured, at a minimum.
# The rest have sensible defaults if left blank or commented out.
#
# See https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#EnvironmentFile=


GANDI_DYNDNS_APIKEY=
GANDI_DYNDNS_DOMAIN=

# OPTIONAL below here
GANDI_DYNDNS_SUBDOMAIN=
GANDI_DYNDNS_TTL=
GANDI_DYNDNS_IPSERVICE=
GANDI_DYNDNS_API=
